### ISSUE TITLE
Every 1 minute entites are unknown and unavailable

### ISSUE THREAD

**Issue by milandzuris** [dougiteixeira/proxmoxve#286] opened 2024-04-09 13:04 UTC
### Checklist

- [X] I have updated to the latest available Proxmox VE Custom Integration version, [see the latest version here](https://github.com/dougiteixeira/proxmoxve/releases/latest).

### Describe the issue you are experiencing

Every 1 minute entites are unknown and unavailable
![image](https://github.com/dougiteixeira/proxmoxve/assets/42905545/1fbf7d27-b907-453d-864c-e0a870f9dac3)

### In which version of Home Assistant Core do you have the problem?

2024.4.2 idk this problem i have longer

### What version of Proxmox VE Custom Integration has the issue?

3.4.1 idk this problem i have longer

### What version of Proxmox VE do you have the problem?

*

**Comment by EpicLPer** [comment] 2024-04-18 06:47
Seems like a duplicate of #280

**Closed** 2024-11-26 02:00 UTC
Labels: bug
