### ISSUE TITLE
Proxmox VE 8.0 upgrade issue - some entities are unavailable

### ISSUE THREAD

**Issue by Coder84619** [dougiteixeira/proxmoxve#99] opened 2023-06-23 03:30 UTC
I upgraded two Proxmox VE 7.4 hosts to 8.0. However, there appears to be a compatibility issue. The old CPU/memory/swap/update  counters are unavailable. But a "fresh" set of counters are available and work. So I have to manually clean up the unavailable entities. Not sure if this is by design or not?

**Comment by jimbytes** [comment] 2023-08-12 16:09
For me, it's not working at all.

**Comment by dougiteixeira** [comment] 2023-08-19 22:32
Can you provide more information please:

* What version of the custom integration are you using?
* Are there any error messages in the logs regarding the Proxmox integration?
* After upgrading to Proxmox 8, did all entities stop working or were they replaced with new working entities?

**Comment by virtualben89** [comment] 2023-08-21 17:52
I run into the same issue. It got it resolved by deleting all entities and devices, added the Proxmox host again and all machines and containers were recognized.

**Comment by dougiteixeira** [comment] 2023-11-05 23:56
@Coder84619 and @virtualben89,

Can you provide more information please:

* What version of the custom integration are you using?
* Are there any error messages in the logs regarding the Proxmox integration?
* After upgrading to Proxmox 8, did all entities stop working or were they replaced with new working entities?

**Comment by dougiteixeira** [comment] 2023-11-09 20:23
I understand this issue was caused by upgrading the integration to version 2.0.
I'm closing this soon, if you have more information, please open a new issue and attach the debug logs.
Thanks.

**Closed by dougiteixeira** 2023-11-09 20:23 UTC
Labels: help wanted, question
